[package]
name = "trans-bot"
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # For exploratory dev.

[dependencies]
# shuttle
shuttle-runtime = "0.44.0"
shuttle-serenity = "0.44.0"

# discord
poise = "0.6.1"

tracing = "0.1.37"
tokio = "1.26.0"
